### ISSUE TITLE
alignment of dates wrong

### ISSUE THREAD

**Issue by FrankMittelbach** [Ri-Ga/typed-checklist#2] opened 2018-11-05 11:40 UTC
maybe a strange example, but the alignments look wrong:

```
\documentclass{article}
\pagestyle{empty}
\setlength\textwidth{251.0pt}

  \usepackage{enumitem}
  \setlist{nosep}

  \setlength\marginparwidth{35pt}
  \addtolength\textwidth{-2\marginparwidth}
  \addtolength\textwidth{-2\marginparsep}

  \setcounter{page}{1}


\usepackage[withAsciilist=true]{typed-checklist}

\begin{document}
\begin{AsciiList}[GoalList,TaskList]{-,*}
- unclear[deadline=1.1.2019]: Packages missing?
- achieved[deadline=1.8.2017]: chapter 2 finished
- open[who=Frank,deadline=1.1.2019]: chapter 3 finished
  * started[who=Frank,label=task]: Report typed-checklist issues
  * done[who=Richard]:%
Correct typed-checklist package from \ref{task}
\end{AsciiList}
\end{document}
```

My result is this:
<img width="491" alt="bildschirmfoto 2018-11-05 um 12 39 25" src="https://user-images.githubusercontent.com/1062981/47996155-e21e9880-e0f7-11e8-971e-b502c8f612d0.png">

**Comment by Ri-Ga** [comment] 2022-05-29 18:56
Looks like the issue is fixed and I just forgot to close this issue back in 2018.

**Closed as completed by Ri-Ga** 2022-05-29 18:56 UTC
